### ISSUE TITLE
Cannot open Unity project correctly

### ISSUE THREAD

**Issue by martindiao** [AlanWills/CelesteUnity#1]
Sorry, but I am new to the Addressables things. I am familiar with projects containing all the resources in the Assets folder but don't know how to open this project. 

Seems like Unity only recognizes the files in the Assets folder. Could you please give some instructions on how to open the project correctly in detail?

**Comment by AlanWills** [comment]
Heya!

So this project doesn't require you use addressables, but does require the addressables package for the code to compile (along with a few other Unity packages).

You should be able to import it through the package manager as a git Package, or clone it into the Assets folder of your project, or download it and copy it into the Assets folder yourself (if doing these last two options, I typically put it in a folder called Celeste just for organization).

What have you tried so far and what difficulties are you running into?

**Comment by martindiao** [comment]
I figured out how to import this repo as a package into a new unity project. There is a menu option 'Celeste' in the editor. 

I don't know how this framework works because there seems to be no art assets to form a demo scene?

**Comment by AlanWills** [comment]
Sorry dude, you're the first person to try and use this other than me, so unfortunately there are no docs for it.

That being said, you're right, and I will try my best to write some forthwith. Is there a particular area you'd be interested, or just a general 'How To'?

Possible areas I can write about:

- Scene Management
- Events and Parameters
- State Machines
- Decoupling your code with this framework
- Mobile Features e.g. Ads, Notifications and Cloud Save
- UI, especially handling variable resolution, easily modifying layouts, dealing with layering and a popup framework
- Addressables and some tools to save you time
- A build system to help make builds more easily

I have a live game that uses an older version of this framework (I think the repo is public on here and called Robbi) and another in development right now using the latest version of the framework called Language-Flashcards (it should also be public).

Feel free to clone those to see how the framework can be used.  I appreciate this isn't an easy way to start, but if I can help, let me know.

**Comment by martindiao** [comment]
Thanks for the explanation. I am learning unity by remaking some famous games. I'm wonder whether it is possible to recreate Celeste using this framework as its name shows?

**Comment by AlanWills** [comment]
Ahh I see the confusion. This framework was actually named and released before the release of the famous video game and is entirely unrelated.

This is just a bunch of tools to help make games with Unity.

**Comment by martindiao** [comment]
That's ok and thanks a lot for your reply. I think I can still learn a thing or two from this framework.

**Comment by martindiao** [comment]
That's ok and thanks a lot for your reply. I think I can still learn a thing or two from this framework.
